/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Controladores.Controlador;
import javax.swing.DefaultListModel;

/**
 *
 * @author Gonza
 */
public class Main extends javax.swing.JFrame {
    DefaultListModel<String> elementosLista = new DefaultListModel<>();
    /**
     * Creates new form NewJFrame
     */
    public Main() {
        
        initComponents();
        setLocationRelativeTo(this);
        Inicializar();
        Lista.setModel(elementosLista);
      
    }
    
    public void Inicializar(){
        //Selecciono el rb de inventario y desabilito los demas
        RbInventario.setSelected(true);
        RbVehiculo.setEnabled(false);
        RbComponente.setEnabled(false);
        //Oculto paneles vehiculo y componentes
        PanelVehiculo.setVisible(false);
        PanelComponentes.setVisible(false);
        //Oculto botones
        btnMostrar.setVisible(false);
        btnGrabar.setVisible(false);
        //Oculto text area
        TextArea.setVisible(false);
        //Se llama rutina para limpiar campos
        limpiarCampos();
        int index = Lista.getSelectedIndex();
        elementosLista.removeAllElements();
    }
    public void limpiarCampos(){
        TfMarca.setText("");
        TfPeso.setText("");
        TfNumero.setText("");
        TfPrecio.setText("");
        TfCilindrada.setText("");
        TfCilindros.setText("");
        TfColor.setText("");
        TextArea.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelActivacion = new javax.swing.JPanel();
        RbInventario = new javax.swing.JRadioButton();
        RbVehiculo = new javax.swing.JRadioButton();
        RbComponente = new javax.swing.JRadioButton();
        PInventario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TfMarca = new javax.swing.JTextField();
        btnInventario = new javax.swing.JButton();
        PanelVehiculo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TfPeso = new javax.swing.JTextField();
        btnVehiculo = new javax.swing.JButton();
        PanelComponentes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TfNumero = new javax.swing.JTextField();
        TfPrecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TfCilindrada = new javax.swing.JTextField();
        TfCilindros = new javax.swing.JTextField();
        TfDescripcion = new javax.swing.JTextField();
        TfColor = new javax.swing.JTextField();
        btnComponente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        btnGrabar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelActivacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Activation"));

        RbInventario.setText("Inventario");
        RbInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbInventarioActionPerformed(evt);
            }
        });

        RbVehiculo.setText("Vehiculo");

        RbComponente.setText("Componente");

        javax.swing.GroupLayout PanelActivacionLayout = new javax.swing.GroupLayout(PanelActivacion);
        PanelActivacion.setLayout(PanelActivacionLayout);
        PanelActivacionLayout.setHorizontalGroup(
            PanelActivacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelActivacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelActivacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RbComponente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RbVehiculo)
                    .addComponent(RbInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PanelActivacionLayout.setVerticalGroup(
            PanelActivacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelActivacionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(RbInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RbVehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RbComponente)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PInventario.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventory"));

        jLabel1.setText("Marca :");

        TfMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfMarcaActionPerformed(evt);
            }
        });

        btnInventario.setText("Crear");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PInventarioLayout = new javax.swing.GroupLayout(PInventario);
        PInventario.setLayout(PInventarioLayout);
        PInventarioLayout.setHorizontalGroup(
            PInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnInventario)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        PInventarioLayout.setVerticalGroup(
            PInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventario))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        PanelVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehicle"));

        jLabel3.setText("Peso :");

        TfPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPesoActionPerformed(evt);
            }
        });

        btnVehiculo.setText("Crear");
        btnVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVehiculoLayout = new javax.swing.GroupLayout(PanelVehiculo);
        PanelVehiculo.setLayout(PanelVehiculoLayout);
        PanelVehiculoLayout.setHorizontalGroup(
            PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnVehiculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelVehiculoLayout.setVerticalGroup(
            PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVehiculo))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        PanelComponentes.setBorder(javax.swing.BorderFactory.createTitledBorder("Components"));

        jLabel4.setText("Numero :");

        jLabel5.setText("Precio :");

        TfNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNumeroActionPerformed(evt);
            }
        });

        jLabel6.setText("MOTOR");
        jLabel6.setToolTipText("");

        jLabel7.setText("CARROCERIA");

        jLabel8.setText("Cilindrada :");

        jLabel9.setText("Cilindros :");

        jLabel10.setText("Descripcion :");

        jLabel11.setText("Color :");

        TfDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfDescripcionActionPerformed(evt);
            }
        });

        TfColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfColorActionPerformed(evt);
            }
        });

        btnComponente.setText("Crear");
        btnComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComponenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelComponentesLayout = new javax.swing.GroupLayout(PanelComponentes);
        PanelComponentes.setLayout(PanelComponentesLayout);
        PanelComponentesLayout.setHorizontalGroup(
            PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(144, 479, Short.MAX_VALUE))
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelComponentesLayout.createSequentialGroup()
                                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(TfCilindros))
                                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TfCilindrada, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                                .addGap(134, 134, 134))
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(TfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TfDescripcion))
                            .addComponent(jLabel7)
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(45, 45, 45)
                                .addComponent(TfColor))
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(41, 41, 41)
                                .addComponent(TfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(37, 37, 37)
                .addComponent(btnComponente)
                .addGap(18, 18, 18))
        );
        PanelComponentesLayout.setVerticalGroup(
            PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(TfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(TfCilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(TfCilindros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComponente))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(Lista);

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane2.setViewportView(TextArea);

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostar en TextArea");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelActivacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGrabar)))
                            .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(PanelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGrabar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelActivacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbInventarioActionPerformed

    private void TfMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfMarcaActionPerformed

    private void TfPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPesoActionPerformed

    private void TfNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNumeroActionPerformed

    private void TfDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfDescripcionActionPerformed

    private void TfColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfColorActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        RbVehiculo.setEnabled(true);
        RbVehiculo.setSelected(true);
        PanelVehiculo.setVisible(true);
        TfMarca.setEditable(false);
        btnInventario.setVisible(false);
        String UnItem = "Inventario";
        elementosLista.addElement(UnItem);
        
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        TextArea.setText("");
        int index = Lista.getSelectedIndex();
        String linea = "";
        switch(index){
            case 0:{
                System.out.println("Inventario");
                linea = linea + TfMarca.getText();
                TextArea.append(linea);
                break;
            }
            case 1:{
                linea = linea + TfPeso.getText();
                System.out.println("Vehiculo");
                TextArea.append(linea);
                break;
            }
            case 2:{
                linea = linea + TfNumero.getText()+ "--" + TfPrecio.getText()+ "--" + TfCilindrada.getText()+
                "--" + TfCilindros.getText()+ "--" + TfDescripcion.getText() + "--" + TfColor.getText();
                System.out.println("Compontentes");
                TextArea.append(linea);
                break;
            }
    }
       
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoActionPerformed
       RbComponente.setEnabled(true);
       RbComponente.setSelected(true);
       PanelComponentes.setVisible(true);
       TfPeso.setEditable(false);
       btnVehiculo.setVisible(false);
       String UnItem = "Vehiculo";
       elementosLista.addElement(UnItem);

    }//GEN-LAST:event_btnVehiculoActionPerformed

    private void btnComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComponenteActionPerformed
       btnComponente.setVisible(false);
       btnGrabar.setVisible(true);
       btnMostrar.setVisible(true);
       TextArea.setVisible(true);
       TfPrecio.setEditable(false);
       TfNumero.setEditable(false);
       TfCilindrada.setEditable(false);
       TfCilindros.setEditable(false);
       TfDescripcion.setEditable(false);
       TfColor.setEditable(false);
       String UnItem = "Componentes";
       elementosLista.addElement(UnItem);
    }//GEN-LAST:event_btnComponenteActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
       int peso = Integer.parseInt(TfPeso.getText());
       int numero = Integer.parseInt(TfNumero.getText());
       float precio = Float.parseFloat(TfPrecio.getText());
       int cantCilindrada = Integer.parseInt(TfCilindrada.getText());
       int cilindros = Integer.parseInt(TfCilindros.getText());
       String marca = TfMarca.getText();
       String descripcion = TfDescripcion.getText();
       String color = TfColor.getText();
       
       Controlador.grabar(marca,peso,numero,precio,cantCilindrada,cilindros,descripcion,color);
       Inicializar();
       btnInventario.setVisible(true);
    }//GEN-LAST:event_btnGrabarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Lista;
    private javax.swing.JPanel PInventario;
    private javax.swing.JPanel PanelActivacion;
    private javax.swing.JPanel PanelComponentes;
    private javax.swing.JPanel PanelVehiculo;
    private javax.swing.JRadioButton RbComponente;
    private javax.swing.JRadioButton RbInventario;
    private javax.swing.JRadioButton RbVehiculo;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JTextField TfCilindrada;
    private javax.swing.JTextField TfCilindros;
    private javax.swing.JTextField TfColor;
    private javax.swing.JTextField TfDescripcion;
    private javax.swing.JTextField TfMarca;
    private javax.swing.JTextField TfNumero;
    private javax.swing.JTextField TfPeso;
    private javax.swing.JTextField TfPrecio;
    private javax.swing.JButton btnComponente;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void SetLocationRelativeTo(Main aThis) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
